version: '3'
services:
  cls-server:
    image: paddlenlp:${RELEASE_TAGS}
    container_name: xiaoyu-models-cls
    command:
      - zero_shot_text_cls.py
    expose:
      - 8099
    restart: unless-stopped

  ner-server:
    image: paddlenlp:${RELEASE_TAGS}
    container_name: xiaoyu-models-ner
    command:
      - information_extraction.py
    expose:
      - 8099
    restart: unless-stopped

  emb-server:
    image: sentence_transformers:${RELEASE_TAGS}
    container_name: xiaoyu-models-emb
    command:
      - semantic_index.py
    expose:
      - 8099
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: xiaoyu-models-proxy
    restart: unless-stopped
    ports:
      - ${MODELS_SERVER_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - cls-server
      - ner-server
      - emb-server

networks:   
  default:
    name: xiaoyu-model-server
